const ADD_USER_REQUEST = 'ADD_USER_REQUEST'
const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'
const ADD_USER_FAIL= 'ADD_USER_FAIL'
const LOGIN_REQUEST='LOGIN_REQUEST'
const LOGIN_SUCCESS='LOGIN_SUCCESS'
const LOGIN_FAIL='LOGIN_FAIL'



export  {ADD_USER_SUCCESS,ADD_USER_REQUEST,ADD_USER_FAIL,LOGIN_SUCCESS,LOGIN_REQUEST,LOGIN_FAIL}